# Generated by Django 5.2 on 2025-09-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='UserPasswordResetToken',
        ),
    ]
